### ISSUE TITLE
UMD build's react bindings pass unwrapped CJS namespace to setDefaultPostHogInstance since 1.407.3

### ISSUE THREAD

**Issue by schinery** [PostHog/posthog-js#4310]
## Bug description

Since 1.407.3, the UMD build of `posthog-js/react` (`react/dist/umd/index.js`) passes the raw `require('posthog-js')` module namespace object to `setDefaultPostHogInstance`, instead of unwrapping its `.default`. This breaks the "global instance" fallback that `usePostHog()` / `useFeatureFlagEnabled()` / etc. use when there's no `<PostHogProvider>` in the tree — which is hit by any CJS/Node consumer that resolves `posthog-js/react` via its `"main"` field (the package has no `"exports"` map), e.g. Jest/Vitest.

Any call like `posthog.capture(...)` or `posthog.isFeatureEnabled(...)` made through that fallback throws `TypeError: ... is not a function`, because the object handed to `setDefaultPostHogInstance` is `{ default: <PostHogInstance>, posthog: <PostHogInstance>, PostHog, ...otherNamedExports }` rather than the instance itself.

Diffing the published UMD bundle between versions:

**1.407.2** (`react/dist/umd/index.js`):
```js
function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
var posthogJs__default = /*#__PURE__*/_interopDefaultLegacy(posthogJs);
...
setDefaultPostHogInstance(posthogJs__default["default"]);
```

**1.407.3** (and still present in the latest, 1.407.6):
```js
setDefaultPostHogInstance(posthogJs);
```

The `_interopDefaultLegacy` helper (and its usage for `posthogJs`) was dropped entirely from the UMD output — looks like a Rollup build-config or Rollup-version change that altered the `output.interop` handling for the `posthog-js` UMD/CJS import. The ESM build (`react/dist/esm/index.js`) is unaffected and byte-for-byte unchanged between 1.407.2 and 1.407.3, so this is UMD-build-specific.

Expected behaviour: `setDefaultPostHogInstance` should receive the actual `PostHog` instance (i.e. `posthogJs.default` / `posthogJs.posthog`), matching 1.407.2's behaviour, so `usePostHog()` and friends work without an explicit `<PostHogProvider>` in CJS/UMD consumers.

## How to reproduce

1. In a Node/CJS context (e.g. a Jest/Vitest test, or any bundler that resolves `posthog-js/react` via its `"main"` field):
   ```js
   const { usePostHog } = require('posthog-js/react');
   // render a component using this hook with no <PostHogProvider> wrapping it
   ```
2. Call a hook that reads the global-instance fallback, e.g. `useFeatureFlagEnabled('some-flag')` or `usePostHog().capture(...)`.
3. Observe `TypeError: client.isFeatureEnabled is not a function` / `TypeError: posthog?.capture is not a function`.

Minimal check — printing what `setDefaultPostHogInstance` actually receives:
```js
const posthogJs = require('posthog-js');
console.log(typeof posthogJs.capture);          // undefined
console.log(typeof posthogJs.default.capture);  // function — this is what should have been passed
```

Versions affected: `posthog-js` 1.407.3 through 1.407.6 (latest checked at time of writing). Last known good: 1.407.2.

Workaround: force resolution of `posthog-js/react`'s ESM build instead of the UMD build in bundlers/test runners that would otherwise pick `"main"` (e.g. Vitest alias: `"posthog-js/react": "posthog-js/react/dist/esm/index.js"`), since the ESM build is unaffected.

## Related sub-libraries

- [ ] All of them
- [x] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [ ] posthog-react-native
- [x] @posthog/react
- [ ] @posthog/ai
- [ ] @posthog/convex
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin

## Additional context

Found while investigating a Dependabot bump of `posthog-js` from 1.407.2 to 1.407.3 in our app, which caused a wave of `TypeError: posthog?.capture is not a function` / `TypeError: client.isFeatureEnabled is not a function` errors in our Vitest suite. Confirmed the regression by swapping `node_modules/posthog-js` between the two versions and re-running the same test — passes on 1.407.2, fails on 1.407.3+. Not a mocking issue on our end: the same shape mismatch occurs with the real (unmocked) package too, since `require('posthog-js')` always returns the CJS module namespace object, not the instance.

**Comment by marandaneto** [comment]
thanks @schinery 
looking into this, looks like a regression by https://github.com/PostHog/posthog-js/pull/4250
