### ISSUE TITLE
Types module not found causing all builds to fail

### ISSUE THREAD

**Issue by kunal-singh** [PostHog/posthog-js#994]
**UPDATE:** We got it to work by using version 1.90.0 for now. But would like to upgrade to the latest one or may be anything near 1.100.0(the latest at the time of writing is 1.104.0)

Hey,

So today morning all our angular app builds using posthog-js version 1.87.0 started breaking. Below is the error that appears on the workflow runs

`
Error: node_modules/posthog-js/dist/module.d.ts:1:62 - error TS2307: Cannot find module 'types' or its corresponding type declarations.
import { MinimalHTTPResponse as MinimalHTTPResponse$1 } from 'types';
`

I have tried the latest version 1.104.4 too.

Has some breaking change been introduced? I can see that a new release went out 18hrs ago.

**Comment by pauldambra** [comment]
Hey Kunal, we avoid breaking changes and use posthog-js ourselves so there's definitely something weird going on here!

I've not used Angular for a few years... what build system does it use now? I'm guessing that you're including it via NPM and this is failing when you run a build command? (I'll need to make an example project to investigate what's happening - or your welcome to - since you'll know angular better than me 😊)

**Comment by pauldambra** [comment]
Ah, just to clarify you have been using 1.87.0 and successfully building and then that stopped working?

Did you make any changes - strange for the build to stop working - the 1.87.0 artefact on NPM is unchanged

**Comment by sergiomilici** [comment]
I have the same issue when installing `1.104.4`. I had to install `1.103.2` to make it work.
I tried a clean install removing `node_modules` folder but the same error happened.

**Comment by kunal-singh** [comment]
Hey Paul,

Yes the v1.87.0 stopped working. And yes it gets pulled through NPM.

I think we made some changes to our dependencies which caused it to break. I'll try reproducing the same on a codesandbox env in some time.

**Comment by pauldambra** [comment]
That would be amazing, thanks @kunal-singh 😍

Hey @sergiomilici, can you share how you're bundling/building? Thanks!

**Comment by haines** [comment]
This appears to have been introduced here: https://github.com/PostHog/posthog-js/pull/898/files#diff-4ec4f8c3a4022f1ceb88eb280fbee6c896c5e94e50a6169a42e4707e67676364R1

I think that should be an import from `"./types"`, not `"types"`. Not sure how that's not breaking the build 🤔
