### PR TITLE
fix: Remove `baseUrl` from TypeScript compiler options

### LINKED ISSUE #994: Types module not found causing all builds to fail
**UPDATE:** We got it to work by using version 1.90.0 for now. But would like to upgrade to the latest one or may be anything near 1.100.0(the latest at the time of writing is 1.104.0)

Hey,

So today morning all our angular app builds using posthog-js version 1.87.0 started breaking. Below is the error that appears on the workflow runs

`
Error: node_modules/posthog-js/dist/module.d.ts:1:62 - error TS2307: Cannot find module 'types' or its corresponding type declarations.
import { MinimalHTTPResponse as MinimalHTTPResponse$1 } from 'types';
`

I have tried the latest version 1.104.4 too.

Has some breaking change been introduced? I can see that a new release went out 18hrs ago.

### PR DESCRIPTION
**Pull request by haines**
## Changes

Fixes #994

`baseUrl` is currently [set to `./src` in `tsconfig.json`](https://github.com/PostHog/posthog-js/blob/54c8a97616cfc9f5cf692cad5eec4251f11be6f3/tsconfig.json#L3), which allows absolute imports of files within the package.

In v1.104.0, this resulted in the compiled `dist/module.d.ts` file [including an import from a spurious `"types"` package](https://app.renovatebot.com/package-diff?name=posthog-js&from=1.103.2&to=1.104.0#d2h-020126) instead of bundling the imported type (possibly because the imports weren't consistent - sometimes absolute and sometimes relative, leading to them being treated as different?).

This PR removes the `baseUrl` setting and replaces the absolute imports that relied on it with relative ones.

### CODE REVIEW

**Review by benjackwhite — APPROVED** [review]
Works fine for me locally and the bundles look good 👍
